BEGIN;
    CREATE TABLE IF NOT EXISTS users
    (
        id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        version integer NOT NULL,
        data text NOT NULL,

        created_at timestamp with time zone DEFAULT now(),
        updated_at timestamp with time zone DEFAULT now(),
        deleted_at timestamp with time zone
    );
COMMIT;
